In [ ]:
import numpy as np
import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt
import io
from google.colab import files

uploaded = files.upload()

Saving iris-sub2-test.csv to iris-sub2-test.csv
Saving iris-sub2-train.csv to iris-sub2-train.csv


In [ ]:
iris_sub2_test = pd.read_csv(io.BytesIO(uploaded['iris-sub2-test.csv']), header = None)
iris_sub2_train = pd.read_csv(io.BytesIO(uploaded['iris-sub2-train.csv']), header = None)

In [ ]:
train_data1 = iris_sub2_train.iloc[0:10,:-1].values
train_data2 = iris_sub2_train.iloc[10:20,:-1].values
train_data3 = iris_sub2_train.iloc[20:30,:-1].values

In [ ]:
train_data3.shape

(10, 4)

In [ ]:
iris_sub2_test.shape

(15, 4)

In [ ]:
mean1 = np.mean(train_data1, 0)
mean2 = np.mean(train_data2, 0)
mean3 = np.mean(train_data3, 0)

cov1 = np.cov(train_data1, rowvar=False)
cov2 = np.cov(train_data2, rowvar=False)
cov3 = np.cov(train_data3, rowvar=False)

In [ ]:
Likeli1 = stats.multivariate_normal.pdf(iris_sub2_test, mean1, cov1)
Likeli2 = stats.multivariate_normal.pdf(iris_sub2_test, mean2, cov2)
Likeli3 = stats.multivariate_normal.pdf(iris_sub2_test, mean3, cov3)

Likeli = np.vstack((Likeli1, Likeli2, Likeli3))

In [ ]:
Likeli

array([[1.39016226e+000, 2.16236844e+000, 1.46083526e-001,
        1.94972676e-006, 6.13936274e-002, 7.13953354e-208,
        1.00997526e-133, 8.50430525e-211, 1.96126406e-139,
        8.01423482e-142, 0.00000000e+000, 1.06288642e-269,
        0.00000000e+000, 8.96133103e-253, 4.44628808e-308],
       [4.99147350e-019, 1.08441561e-020, 2.41759363e-025,
        3.20399997e-015, 1.15311788e-015, 7.53198298e-002,
        1.66648118e+000, 2.31952115e-001, 2.18788939e-001,
        1.36543750e+000, 9.06046212e-006, 2.04437409e-004,
        9.92941912e-011, 5.34577831e-002, 2.38936941e-004],
       [1.58446669e-034, 4.49973812e-032, 3.48078702e-034,
        9.21086236e-028, 2.79013176e-022, 2.15825724e-001,
        2.57704472e-006, 8.91563434e-002, 6.18337496e-003,
        4.34625368e-006, 7.41109933e-001, 2.07708656e-001,
        2.25286594e-001, 2.48865514e-001, 1.10532041e+000]])

In [ ]:
Class = np.argmax(Likeli, 0)
Labels = np.array([0,0,0,0,0,1,1,1,1,1,2,2,2,2,2])
Results = np.equal(Class, Labels)
err_rate = 1 - np.count_nonzero(Results)/15

In [ ]:
Results

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [ ]:
Class

array([0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [ ]:
np.argmax(Likeli)

1

In [ ]:
err_rate

0.06666666666666665

In [ ]:
import numpy as np    
A = np.matrix([[1,2,3,33],[4,5,6,66],[7,8,9,99]])

np.argmax(A)  # 11, which is the position of 99

np.argmax(A[:,:])  # 11, which is the position of 99

np.argmax(A[:1])  # 3, which is the position of 33

np.argmax(A[:,2])  # 2, which is the position of 9

np.argmax(A[1:,2])  # 1, which is the position of 9

1

In [ ]:
A[1,1]

5

In [ ]:
np.argmax(A[:,:]) 

11

In [ ]:
A

matrix([[ 1,  2,  3, 33],
        [ 4,  5,  6, 66],
        [ 7,  8,  9, 99]])